<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            'United States',
            'United Kingdom',
            'Canada',
            'Australia',
            'Germany',
            'France',
            'Italy',
            'Spain',
            'Netherlands',
            'Switzerland',
            'Sweden',
            'Norway',
            'Denmark',
            'Finland',
            'Belgium',
            'Austria',
            'Ireland',
            'New Zealand',
            'Japan',
            'South Korea',
            'China',
            'India',
            'Singapore',
            'Malaysia',
            'Thailand',
            'Indonesia',
            'Philippines',
            'Vietnam',
            'Brazil',
            'Argentina',
            'Mexico',
            'South Africa',
            'Egypt',
            'Israel',
            'United Arab Emirates',
            'Saudi Arabia',
            'Qatar',
            'Kuwait',
            'Bahrain',
            'Oman',
            'Turkey',
            'Greece',
            'Portugal',
            'Poland',
            'Czech Republic',
            'Hungary',
            'Romania',
            'Russia',
            'Ukraine',
            'Maldives',
            'Sri Lanka',
            'Bangladesh',
            'Pakistan',
            'Nepal',
            'Myanmar',
            'Cambodia',
            'Laos',
            'Taiwan',
            'Hong Kong',
            'Macau',
            'Chile',
            'Colombia',
            'Peru',
            'Ecuador',
            'Venezuela',
            'Uruguay',
            'Paraguay',
            'Costa Rica',
            'Panama',
            'Belize',
            'Jamaica',
            'Bahamas',
            'Barbados',
            'Trinidad and Tobago',
            'Fiji',
            'Papua New Guinea',
            'Solomon Islands',
            'Vanuatu',
            'Palau',
            'Micronesia',
            'Marshall Islands',
            'Tonga',
            'Samoa',
            'Cook Islands',
            'Croatia',
            'Iceland',
            'Luxembourg',
            'Monaco',
            'Malta',
            'Cyprus',
            'Estonia',
            'Latvia',
            'Lithuania',
            'Slovenia',
            'Slovakia',
            'Bulgaria',
            'Serbia',
            'Montenegro',
            'Bosnia and Herzegovina',
            'Macedonia',
            'Albania',
            'Morocco',
            'Tunisia',
            'Jordan',
            'Lebanon',
            'Iraq',
            'Iran',
            'Afghanistan',
            'Kazakhstan',
            'Uzbekistan',
            'Mongolia',
            'Bhutan',
            'Brunei',
            'East Timor',
            'Mauritius',
            'Seychelles',
            'Madagascar',
            'Tanzania',
            'Kenya',
            'Mozambique',
            'Zimbabwe',
            'Botswana',
            'Namibia',
            'Angola',
            'Ghana',
            'Nigeria',
            'Senegal',
            'Ivory Coast',
            'Cameroon',
            'Gabon',
            'Republic of the Congo',
            'Democratic Republic of the Congo',
            'Ethiopia',
            'Sudan',
            'Libya',
            'Algeria',
            'Chad',
            'Niger',
            'Mali',
            'Burkina Faso',
            'Guinea',
            'Sierra Leone',
            'Liberia',
            'Togo',
            'Benin',
            'Guinea-Bissau',
            'Gambia',
            'Cape Verde',
            'São Tomé and Príncipe',
            'Equatorial Guinea',
            'Central African Republic',
            'Rwanda',
            'Burundi',
            'Uganda',
            'Djibouti',
            'Eritrea',
            'Somalia',
            'Malawi',
            'Zambia',
            'Lesotho',
            'Swaziland',
            'Comoros',
            'Mauritius',
            'Seychelles',
            'Cuba',
            'Dominican Republic',
            'Haiti',
            'Puerto Rico',
            'Guadeloupe',
            'Martinique',
            'Barbados',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Grenada',
            'Dominica',
            'Antigua and Barbuda',
            'Saint Kitts and Nevis',
            'Guyana',
            'Suriname',
            'French Guiana',
            'Bolivia',
            'French Polynesia',
            'New Caledonia',
            'Guam',
            'Northern Mariana Islands',
            'American Samoa',
            'Palestine',
            'Yemen',
            'Oman',
            'Djibouti',
            'Somalia',
            'Eritrea',
            'South Sudan',
            'Western Sahara',
        ];

        foreach ($countries as $country) {
            Country::firstOrCreate(
                ['name' => $country],
                ['name' => $country]
            );
        }

        $this->command->info('Countries seeded successfully!');
    }
}

